# Generated by Django 6.1.1 on 2026-09-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van')], max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('service_area', models.CharField(blank=True, max_length=150)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='accounts.profile')),
            ],
            options={
                'ordering': ['profile__user__username'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['is_available'], name='delivery_co_is_avai_ce01f7_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='delivery_de_status_6efeaa_idx'),
        ),
    ]
