# Generated by Django 6.1.1 on 2026-09-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bicicleta'), ('motorcycle', 'Motocicleta'), ('car', 'Auto'), ('van', 'Camioneta')], max_length=20, verbose_name='tipo de vehículo')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='patente')),
                ('is_available', models.BooleanField(default=False, verbose_name='disponible')),
                ('service_area', models.CharField(blank=True, max_length=150, verbose_name='zona de servicio')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='accounts.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'Transportador',
                'verbose_name_plural': 'Transportadores',
                'ordering': ['profile__user__username'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('picked_up', 'Retirado'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado')], default='pending', max_length=20, verbose_name='estado')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de retiro')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courier', verbose_name='transportador')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['is_available'], name='delivery_co_is_avai_ce01f7_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='delivery_de_status_6efeaa_idx'),
        ),
    ]
