# Generated by Django 6.1.1 on 2026-09-26 16:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150, verbose_name='nombre del negocio')),
                ('tax_id', models.CharField(max_length=30, unique=True, verbose_name='CUIT')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='locations.address', verbose_name='dirección')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='accounts.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramo'), ('box', 'Caja'), ('unit', 'Unidad')], max_length=20, verbose_name='unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='agro.producer', verbose_name='productor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['business_name'], name='agro_produc_busines_9f4159_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['producer'], name='agro_produc_produce_5ff4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='agro_produc_name_9f01b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('producer', 'name'), name='unique_product_per_producer'),
        ),
    ]
