# Generated by Django 6.1.1 on 2026-09-16 17:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('tax_id', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='locations.address')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='accounts.profile')),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('box', 'Box'), ('unit', 'Unit')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='agro.producer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['business_name'], name='agro_produc_busines_9f4159_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['producer'], name='agro_produc_produce_5ff4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='agro_produc_name_9f01b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('producer', 'name'), name='unique_product_per_producer'),
        ),
    ]
