# Generated by Django 6.1.1 on 2026-09-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('consumer', 'Consumidor'), ('producer', 'Productor'), ('courier', 'Transportador'), ('warehouse_manager', 'Encargado de bodega')], default='consumer', max_length=30, verbose_name='rol')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('avatar', models.URLField(blank=True, verbose_name='avatar')),
                ('default_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='locations.address', verbose_name='dirección predeterminada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx')],
            },
        ),
    ]
