# Generated by Django 6.1.1 on 2026-09-16 17:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agro', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='agro.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'product__name'],
                'indexes': [models.Index(fields=['warehouse'], name='inventory_i_warehou_7b4b67_idx'), models.Index(fields=['product'], name='inventory_i_product_8c36d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_product_per_warehouse')],
            },
        ),
    ]
