# Generated by Django 6.1.1 on 2026-09-16 17:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['restaurant__name', 'name'],
                'indexes': [models.Index(fields=['restaurant'], name='menus_resta_restaur_87bda8_idx'), models.Index(fields=['name'], name='menus_resta_name_376651_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_menu_item_per_restaurant')],
            },
        ),
    ]
