# Generated by Django 6.1.1 on 2026-09-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agro', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='locations.address')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='agro.producer')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['producer'], name='warehouses__produce_97edbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('producer', 'name'), name='unique_warehouse_per_producer')],
            },
        ),
    ]
