# Generated by Django 6.1.1 on 2026-09-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='calle')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='provincia')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='código postal')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['city', 'street', 'number'],
                'indexes': [models.Index(fields=['owner'], name='locations_a_owner_i_2d0cde_idx'), models.Index(fields=['city'], name='locations_a_city_b2b186_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='one_default_address_per_user')],
            },
        ),
    ]
